gui:
    expandFocusedSidePanel: true
git:
    paging:
        colorArg: never
        pager: delta --dark --paging=never
    log:
        showWholeGraph: true
os:
  edit: 'nvim'
  editAtLine: '{{editor}} +{{line}} -- {{filename}}'
