gui:
  expandFocusedSidePanel: true
git:
  paging:
    colorArg: never
    pager: delta --dark --paging=never
  log:
    showWholeGraph: true
os:
  edit: "nvim"
  editAtLine: "{{editor}} +{{line}} -- {{filename}}"

customCommands:
  - key: "C"
    command: "git cz"
    description: "commit with commitizen"
    context: "files"
    loadingText: "opening commitizen commit tool"
    subprocess: true
